resource "aws_key_pair" "deployer" {
  key_name   = "Lucas-key"
  public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCfns80vz+BpLgdSNXECByjuXvL7ne7XmQTVy+O1eRKeWMbWjXLf+b6kOrAQgYnBLaHaa1EWgDI7sEC28VwzBzqPZ4bQAvYkYxAwpliHAyfYY6Tc7DB3t/xuewfnVk18SxnpHO6/VOpfKdUAGbWBzqdV9TAMV/RMZcnfYReH6WKKz3ayv6XGWkajGbYuaFvGQutUYUGmTrdDMSFc2QxYqiAy1owUMNEo31XTPvQg5XFuNdxJ2lUNYENONdW3G1GnURWwAfkBOVhjNTk6LMvwWxBtn8oys2l70D7Kf//nb89wmQazuHYrVy+LiduNqeN5lQPyugeavtAnqPD6KwJI4Fx2AKKxgyUBSD6R2ZI9DTA78u252Y+p5p/W83jZzWabQSAD9tMMVBLrvhb3Jy5zZVmGK7rsKxqdwAyaCKxwR7T1WxmJTytfCB+PVRiwwNxZvM/wQeIcTaWwtny8LUeKvZFpymQWoVMGCntojZ4ZlukIEYFHnqTjSHRNdjN+KUQec= soooverpowered@Lucas-Laptop.localdomain"
}
